import { Theme } from "@mui/material";
import { alpha } from "@mui/material/styles";

// Define base color palette
export const baseColors = {
  primary: "#30b3ff",
  secondary: "#dc004e",
  white: "#ffffff",
  black: "#000000",
  bronze: "#BA8C63",
};

// Define semantic color usage
export const colors = {
  primary: {
    main: baseColors.primary,
    light: "", // Will be generated by MUI theme
    dark: "", // Will be generated by MUI theme
  },
  secondary: {
    main: baseColors.secondary,
    light: "", // Will be generated by MUI theme
    dark: "", // Will be generated by MUI theme
  },
  text: {
    primary: baseColors.white,
    secondary: (theme: Theme) => alpha(baseColors.white, 0.8),
    subtle: (theme: Theme) => alpha(baseColors.white, 0.7),
    muted: (theme: Theme) => alpha(baseColors.white, 0.5),
  },
  background: {
    main: "linear-gradient(135deg, rgba(0,0,0,0.1) 0%, rgba(0,0,0,0.2) 100%)",
    card: (theme: Theme) => alpha(theme.palette.common.black, 0.3),
    cardHover: (theme: Theme) => alpha(theme.palette.common.black, 0.4),
    glass: (theme: Theme) => alpha(theme.palette.common.black, 0.3),
  },
  border: {
    light: (theme: Theme) =>
      `1px solid ${alpha(theme.palette.common.white, 0.1)}`,
    medium: (theme: Theme) =>
      `1px solid ${alpha(theme.palette.common.white, 0.2)}`,
    primary: (theme: Theme) =>
      `1px solid ${alpha(theme.palette.primary.main, 0.3)}`,
    dashed: (theme: Theme) =>
      `1px dashed ${alpha(theme.palette.common.white, 0.2)}`,
  },
  status: {
    success: "#4caf50",
    warning: "#ff9800",
    error: "#f44336",
    info: "#2196f3",
  },
  medal: {
    gold: "#ff9800", // warning color
    silver: "#9e9e9e", // grey color
    bronze: baseColors.bronze,
  },
};

// Function to get color with opacity
export const withAlpha = (color: string, opacity: number) => (theme: Theme) =>
  alpha(color, opacity);
